name: bootstrap_icons
description: Bootstrap Icons for Flutter
version: 1.9.1
homepage: https://github.com/ricardodalarme/Bootstrap-Icons-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=0.1.2"

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: Bootstrap Icons
      fonts:
        - asset: fonts/bootstrap-icons.ttf
